version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.17.3
    steps:
      - checkout
      - run:
          name: Install Package alsa
          command: sudo apt install libasound2-dev
      - run:
          name: Run tests
          command: go test -v
      - run:
          name: Build binary
          command: go build